export const TODAY = "2026-04-07";

export const EVENTS = [
  {
    id: 1,
    seriesNumber: "1/8",
    theme: "Boxing",
    owner: "Sandy",
    eventDate: "2026-04-26",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-03-22", done: true },
      { label: "Venue Locked", date: "2026-03-29", done: true },
      { label: "Kickoff", date: "2026-04-05", done: true },
      { label: "Final Check", date: "2026-04-20", done: false },
      { label: "Event Day", date: "2026-04-26", done: false },
    ],
  },
  {
    id: 2,
    seriesNumber: "2/8",
    theme: "Improv",
    owner: "Patrice",
    eventDate: "2026-05-03",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-03-29", done: true },
      { label: "Venue Locked", date: "2026-04-05", done: true },
      { label: "Kickoff", date: "2026-04-12", done: false },
      { label: "Final Check", date: "2026-04-27", done: false },
      { label: "Event Day", date: "2026-05-03", done: false },
    ],
  },
  {
    id: 3,
    seriesNumber: "3/8",
    theme: "Baking",
    owner: "Patrice",
    eventDate: "2026-05-10",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-04-05", done: true },
      { label: "Venue Locked", date: "2026-04-12", done: false },
      { label: "Kickoff", date: "2026-04-19", done: false },
      { label: "Final Check", date: "2026-05-04", done: false },
      { label: "Event Day", date: "2026-05-10", done: false },
    ],
  },
  {
    id: 4,
    seriesNumber: "4/8",
    theme: "Painting",
    owner: "Patrice",
    eventDate: "2026-05-24",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-04-19", done: false },
      { label: "Venue Locked", date: "2026-04-26", done: false },
      { label: "Kickoff", date: "2026-05-03", done: false },
      { label: "Final Check", date: "2026-05-18", done: false },
      { label: "Event Day", date: "2026-05-24", done: false },
    ],
  },
  {
    id: 5,
    seriesNumber: "5/8",
    theme: "Social / Bingo",
    owner: "Sandy",
    eventDate: "2026-05-31",
    tentative: true,
    milestones: [
      { label: "Alignment", date: "2026-04-26", done: false },
      { label: "Venue Locked", date: "2026-05-03", done: false },
      { label: "Kickoff", date: "2026-05-10", done: false },
      { label: "Final Check", date: "2026-05-25", done: false },
      { label: "Event Day", date: "2026-05-31", done: false },
    ],
  },
  {
    id: 6,
    seriesNumber: "6/8",
    theme: "TBD",
    owner: "TBD",
    eventDate: "2026-06-07",
    tentative: true,
    milestones: [
      { label: "Alignment", date: "2026-05-03", done: false },
      { label: "Venue Locked", date: "2026-05-10", done: false },
      { label: "Kickoff", date: "2026-05-17", done: false },
      { label: "Final Check", date: "2026-06-01", done: false },
      { label: "Event Day", date: "2026-06-07", done: false },
    ],
  },
  {
    id: 7,
    seriesNumber: "7/8",
    theme: "TBD",
    owner: "TBD",
    eventDate: "2026-06-21",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-05-17", done: false },
      { label: "Venue Locked", date: "2026-05-24", done: false },
      { label: "Kickoff", date: "2026-05-31", done: false },
      { label: "Final Check", date: "2026-06-15", done: false },
      { label: "Event Day", date: "2026-06-21", done: false },
    ],
  },
  {
    id: 8,
    seriesNumber: "8/8",
    theme: "TBD",
    owner: "TBD",
    eventDate: "2026-06-28",
    tentative: false,
    milestones: [
      { label: "Alignment", date: "2026-05-24", done: false },
      { label: "Venue Locked", date: "2026-05-31", done: false },
      { label: "Kickoff", date: "2026-06-07", done: false },
      { label: "Final Check", date: "2026-06-22", done: false },
      { label: "Event Day", date: "2026-06-28", done: false },
    ],
  },
];

export const MARKETING = [
  {
    id: 1,
    weekLabel: "Apr 7-12",
    weekStart: "2026-04-07",
    event: "Boxing",
    platform: "Instagram",
    type: "Hype reel",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 2,
    weekLabel: "Apr 7-12",
    weekStart: "2026-04-07",
    event: "Boxing",
    platform: "TikTok",
    type: "Behind the scenes clip",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 3,
    weekLabel: "Apr 7-12",
    weekStart: "2026-04-07",
    event: "Boxing",
    platform: "Flock",
    type: "Event announcement",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 4,
    weekLabel: "Apr 13-19",
    weekStart: "2026-04-13",
    event: "Boxing",
    platform: "Instagram",
    type: "Countdown post",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 5,
    weekLabel: "Apr 13-19",
    weekStart: "2026-04-13",
    event: "Boxing",
    platform: "TikTok",
    type: "Cohost intro",
    status: "todo",
    owner: "Sandy",
  },
  {
    id: 6,
    weekLabel: "Apr 13-19",
    weekStart: "2026-04-13",
    event: "Improv",
    platform: "Instagram",
    type: "Teaser post",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 7,
    weekLabel: "Apr 20-26",
    weekStart: "2026-04-20",
    event: "Boxing",
    platform: "Instagram",
    type: "Final push",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 8,
    weekLabel: "Apr 20-26",
    weekStart: "2026-04-20",
    event: "Boxing",
    platform: "TikTok",
    type: "Day-of story",
    status: "todo",
    owner: "Andy",
  },
  {
    id: 9,
    weekLabel: "Apr 27-May 3",
    weekStart: "2026-04-27",
    event: "Improv",
    platform: "Instagram",
    type: "Kickoff post",
    status: "todo",
    owner: "Patrice",
  },
  {
    id: 10,
    weekLabel: "Apr 27-May 3",
    weekStart: "2026-04-27",
    event: "Improv",
    platform: "TikTok",
    type: "Prep teaser",
    status: "todo",
    owner: "Andy",
  },
];

export const BREAK_MARKERS = [
  {
    id: "break-week",
    date: "2026-05-17",
    title: "Break week",
    details: "No public event scheduled.",
  },
];

export const VACATION_BLOCKS = [
  {
    id: "sandy-gone",
    owner: "Sandy",
    label: "Sandy gone",
    tone: "rose",
    start: "2026-04-01",
    end: "2026-04-12",
    details: "Away through April 12",
  },
  {
    id: "sandy-back",
    owner: "Sandy",
    label: "Sandy back",
    tone: "rose",
    end: "2026-04-13",
    start: "2026-04-13",
    details: "Return day",
  },
  {
    id: "patrice-gone",
    owner: "Patrice",
    label: "Patrice gone",
    tone: "cyan",
    start: "2026-03-26",
    end: "2026-04-07",
    details: "Away through April 7",
  },
  {
    id: "patrice-return",
    owner: "Patrice",
    label: "Patrice back",
    tone: "cyan",
    start: "2026-04-08",
    end: "2026-04-08",
    details: "Return day",
  },
  {
    id: "andy-sf",
    owner: "Andy",
    label: "Andy SF",
    tone: "mint",
    start: "2026-04-04",
    end: "2026-04-14",
    details: "Away in SF through April 14",
  },
  {
    id: "andy-back",
    owner: "Andy",
    label: "Andy back",
    tone: "mint",
    start: "2026-04-15",
    end: "2026-04-15",
    details: "Return day",
  },
];
